### ISSUE TITLE
analyticsrelationships is installed but says it's not. main-v1.7.2 

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#312]
![2021-06-14_08-24](https://user-images.githubusercontent.com/44535257/121891920-144df900-ccea-11eb-937d-3742c3595823.png)
![2021-06-14_08-26](https://user-images.githubusercontent.com/44535257/121891989-2b8ce680-ccea-11eb-80e4-1eff3dda27f2.png)

**Comment by gprime31** [comment]
=====================================================
Interlace v1.9.5        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
  0%|                                                                                                                                                                                         | 0/1 [00:00<?, ?it/s][08:43:47] [THREAD] [analyticsrelationships --url https://lredacted.com > .tmp/output_analytics/https://redacted.com.txt] Added to Queue 
/usr/bin/bash: line 1: .tmp/output_analytics/https://redacted.com.txt: No such file or directory
Generated 1 commands in total
Repeat set to 1
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 161.99it/s]
find: ‘output_analytics/’: No such file or directory

**Comment by gprime31** [comment]
same on large sites ^^^ always the same error.

**Comment by six2dez** [comment]
Seems that it is not compiling the tool correctly, I will publish fix asap

**Comment by six2dez** [comment]
Fixed, plz update running ./install.sh

https://github.com/six2dez/reconftw/commit/95995845c495bcc930af8353df251762cfe54af4

**Comment by gprime31** [comment]
Now getting:
Unable to install analyticsrelationships, try manually (5/29)

**Comment by gprime31** [comment]
and:
./install.sh: line 242: syntax error near unexpected token `done'
./install.sh: line 242: `done'

**Comment by six2dez** [comment]
Fixed the installers typo, about the tool try to run manually `go get github.com/six2dez/analyticsrelationships`

**Comment by Nithissh0708** [comment]
Go 1.15 can't analytics relationship

**Comment by gprime31** [comment]
go: downloading github.com/six2dez/analyticsrelationships v0.0.0-20210614141247-519d064ad97a
go get: github.com/six2dez/analyticsrelationships@none updating to
        github.com/six2dez/analyticsrelationships@v0.0.0-20210614141247-519d064ad97a: parsing go.mod:
        module declares its path as: analyticsrelationships
                but was required as: github.com/six2dez/analyticsrelationships

**Comment by gprime31** [comment]
update: the newest version works fine on debian based systems:
#######################################################################
 Checking installed tools 

 Good! All installed! 

 Tools check finished
####################################################################### 

on arch based still get the same error of not installed and the one I posted abuve.

**Comment by Nithissh0708** [comment]
It works

**Comment by six2dez** [comment]
I found the problem, is already pushed to dev branch
