### ISSUE TITLE
Web Server Does Not Start

### ISSUE THREAD

**Issue by kpratik9** [six2dez/reconftw#752]
After running the following command, I am unable to visit web interface:

./reconftw.sh --web-server start

Tried options 2 and 3 for installation but unable visit web interface on port 8001

Starting web server... 
 Web server started! 
 Service Address: http://xxx.xxx.xxx.xxx:8001

I have installed this framework on my cloud VPS. Config is 4vCPU and 8 GB RAM
Linux 5.4.0-155-generic #172-Ubuntu SMP Fri 2023 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

Kindly resolve this issue as early as possible.

**Comment by A-khateeb** [comment]
Same as me it is not working as well

**Comment by six2dez** [comment]
I don't know why that worked for you, because there is no `bin` path inside `web` folder :/

**Comment by six2dez** [comment]
I pushed some changes, could you test again with a fresh installation? @kpratik9

**Comment by kpratik9** [comment]
3. Setup Web Interface (User Interaction needed!)

 4. Exit

#######################################################################

 Insert option: 3


#######################################################################

 Running: Installing web reconftw 

 Installing python libraries...

 python virtualenv install...

[ERROR] Failed to create virtualenv. Please install requirements mentioned in Documentation.

pip3 install -r requirements.txt 
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by VikzSharma** [comment]
> I don't know why that worked for you, because there is no `bin` path inside `web` folder :/

I created the virtual env myself I guess in that directory. Not sure I forget it. Anyways Thanks for this fantastic tool! Appreciated!

**Comment by A-khateeb** [comment]
It worked on my side @six2dez

**Comment by jpassisalves** [comment]
It's like this for me too, I can't access the web server since the first update, I thought that after a few updates it would solve it, but I still can't (I just installed the tool, it's 100% up to date)

~/reconftw# ./reconftw.sh --web-server start

╦═╗┌─┐┌─┐┌─┐┌┐┌╔═╗╔╦╗╦ ╦
╠╦╝├┤ │  │ ││││╠╣  ║ ║║║
╩╚═└─┘└─┘└─┘┘└┘╚   ╩ ╚╩╝
 main-v2.7-47-gf0eb4c8                                 by @six2dez
 Web Interface    by @lur1el, @d3vchac, @mx61tt and @dd4n1b0y

 Starting web server...
 Web server started!
 Service Address: http://x.x.x.x:8001
 
and when I try to access:

 Unable to reach this site
 The connection to x.x.x.x was refused.

(I hid my VPS IP)

**Comment by kpratik9** [comment]
> It's like this for me too, I can't access the web server since the first update, I thought that after a few updates it would solve it, but I still can't (I just installed the tool, it's 100% up to date)
> 
> ~/reconftw# ./reconftw.sh --web-server start
> 
> ╦═╗┌─┐┌─┐┌─┐┌┐┌╔═╗╔╦╗╦ ╦ ╠╦╝├┤ │ │ ││││╠╣ ║ ║║║ ╩╚═└─┘└─┘└─┘┘└┘╚ ╩ ╚╩╝ main-v2.7-47-gf0eb4c8 by @six2dez Web Interface by @lur1el, @d3vchac, @mx61tt and @dd4n1b0y
> 
> Starting web server... Web server started! Service Address: http://x.x.x.x:8001
> 
> and when I try to access:
> 
> Unable to reach this site The connection to x.x.x.x was refused.
> 
> (I hid my VPS IP)

Hi,

What is the configuration of your VPS?

**Comment by kpratik9** [comment]
root@vultr:~/reconftw# ./reconftw.sh --web-server start

 ______                         _______ _______ _  _  _   
(_____ \                       (_______|_______|_)(_)(_)  
 _____) )_____  ____ ___  ____  _____      _    _  _  _   
|  __  /| ___ |/ ___) _ \|  _ \|  ___)    | |  | || || |  
| |  \ \| ____( (__| |_| | | | | |        | |  | || || |  
|_|   |_|_____)\____)___/|_| |_|_|        |_|   \_____/                                                             
 main-v2.7-47-gf0eb4c8                                 by @six2dez
 Web Interface    by @lur1el, @d3vchac, @mx61tt and @dd4n1b0y 

 Server IP address not found.

 Check if the server has internet connection.

**Comment by ErhanKarabulut** [comment]
Same problem here .

**Comment by cryptovert** [comment]
> It's like this for me too, I can't access the web server since the first update, I thought that after a few updates it would solve it, but I still can't (I just installed the tool, it's 100% up to date)
> 
> ~/reconftw# ./reconftw.sh --web-server start
> 
> ╦═╗┌─┐┌─┐┌─┐┌┐┌╔═╗╔╦╗╦ ╦ ╠╦╝├┤ │ │ ││││╠╣ ║ ║║║ ╩╚═└─┘└─┘└─┘┘└┘╚ ╩ ╚╩╝ main-v2.7-47-gf0eb4c8 by @six2dez Web Interface by @lur1el, @d3vchac, @mx61tt and @dd4n1b0y
> 
> Starting web server... Web server started! Service Address: http://x.x.x.x:8001
> 
> and when I try to access:
> 
> Unable to reach this site The connection to x.x.x.x was refused.
> 
> (I hid my VPS IP)

Check if you have firewall rules preventing access.

**Comment by cryptovert** [comment]
While I'm here, credentials for the web-ui anyone?

**Comment by WhiteyCookie** [comment]
I found a workaround which worked for me. 
Replace "ipAddress=$(curl -s ifconfig.me)" at line 2811 in "reconftw.sh" 
with
"ipAddress="127.0.0.1"

(i also changed the port at line 2818 to "8081" but i do think its optional)

**Comment by nicola-pesavento** [comment]
> 3. Setup Web Interface (User Interaction needed!)
> 4. Exit
> 
> #######################################################################
> 
> Insert option: 3
> 
> #######################################################################
> 
> Running: Installing web reconftw
> 
> Installing python libraries...
> 
> python virtualenv install...
> 
> [ERROR] Failed to create virtualenv. Please install requirements mentioned in Documentation.
> 
> pip3 install -r requirements.txt error: externally-managed-environment
> 
> × This environment is externally managed ╰─> To install Python packages system-wide, try apt install python3-xyz, where xyz is the package you are trying to install.
> 
> ```
> If you wish to install a non-Debian-packaged Python package,
> create a virtual environment using python3 -m venv path/to/venv.
> Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
> sure you have python3-full installed.
> 
> If you wish to install a non-Debian packaged Python application,
> it may be easiest to use pipx install xyz, which will manage a
> virtual environment for you. Make sure you have pipx installed.
> 
> See /usr/share/doc/python3.11/README.venv for more information.
> ```
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification.

With Debian, I solved this issue running the following command: `apt install python3-virtualenv`
Then, I run `./install.sh` from _reconftw_ folder and select the option _3 ("Setup Web Interface")_.
To start the web server: `./reconftw.sh --web-server start`.

**Comment by six2dez** [comment]
> > 3. Setup Web Interface (User Interaction needed!)
> > 4. Exit
> > 
> > #######################################################################
> > Insert option: 3
> > #######################################################################
> > Running: Installing web reconftw
> > Installing python libraries...
> > python virtualenv install...
> > [ERROR] Failed to create virtualenv. Please install requirements mentioned in Documentation.
> > pip3 install -r requirements.txt error: externally-managed-environment
> > × This environment is externally managed ╰─> To install Python packages system-wide, try apt install python3-xyz, where xyz is the package you are trying to install.
> > ```
> > If you wish to install a non-Debian-packaged Python package,
> > create a virtual environment using python3 -m venv path/to/venv.
> > Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
> > sure you have python3-full installed.
> > 
> > If you wish to install a non-Debian packaged Python application,
> > it may be easiest to use pipx install xyz, which will manage a
> > virtual environment for you. Make sure you have pipx installed.
> > 
> > See /usr/share/doc/python3.11/README.venv for more information.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification.
> 
> With Debian, I solved this issue running the following command: `apt install python3-virtualenv` Then, I run `./install.sh` from _reconftw_ folder and select the option _3 ("Setup Web Interface")_. To start the web server: `./reconftw.sh --web-server start`.

Added python3-virtualenv to installer for Debian-based distros.

**Comment by DrorDvash** [comment]
I'm using the Docker installation (docker hub), and i've change the entrypoint to be /bin/bash, in order the docker will stay UP and i will be able to change the files in the filesystem (amass config, subfinder etc..)
Anyway, in the docker version you need to install screen because it's not installed, and that's why the web interface is not working out of the box.

### Flow:
This is the first time i'm trying to start the web interface (after running the setup):
port 8001 is not listening.
![image](https://github.com/six2dez/reconftw/assets/8413651/5f63efce-97b8-4770-8c23-c57dc2dc9302)

so i checked what is happening in the source code:
![image](https://github.com/six2dez/reconftw/assets/8413651/59a2dd8d-a2ee-4538-a3d6-8dbfaf7cb7a8)

i tried it my self, and notice there is no screen installed:
![image](https://github.com/six2dez/reconftw/assets/8413651/89ece58a-38e5-4375-b144-fc14c12b65a9)

so i ran `apt install screen`
![image](https://github.com/six2dez/reconftw/assets/8413651/4b0db2f0-b353-4b67-8a8e-410efb81fff1)

Change the ip to be 0.0.0.0 in line 2818 in reconftw.sh
![image](https://github.com/six2dez/reconftw/assets/8413651/b0c3b578-48c8-4af6-be54-f51d3f7cf031)

and it worked :) i can now access the web interface (of course i have also exposed port 8001 from the docker with the host)
![image](https://github.com/six2dez/reconftw/assets/8413651/30a4fa42-5c3f-4980-82df-bdcc62da0d86)


@six2dez please see the fix, all you need is to install screen and change the ip address.

and for docker users - you should think about us will aren't able to set up the internal api-keys for the tools (amass, subfinder, etc...)

**Comment by six2dez** [comment]
Hi all, the web server will be discontinued and will not receive support anymore, next releases will not have the web server on the code.

**Comment by DrorDvash** [comment]
> Hi all, the web server will be discontinued and will not receive support anymore, next releases will not have the web server on the code.

Oh, , why do you cancel it completely? To tell the truth (and it's just on my side of course), I'm here for the dashboard so that i can show results comfortably to team leader / manager.

**Comment by six2dez** [comment]
> > Hi all, the web server will be discontinued and will not receive support anymore, next releases will not have the web server on the code.
> 
> Oh, , why do you cancel it completely? To tell the truth (and it's just on my side of course), I'm here for the dashboard so that i can show results comfortably to team leader / manager.

I'm not going to provide support or fixes for the frontend, and no one wants to take the responsibility of that seriously, so I'd rather not provide the web interface than provide it broken
